---
title: "{{< meta gh.repo >}}: {{< meta tagline >}}"
---

{{< include /docs/includes/_badges.qmd >}}

This is a template for creating a new repository for Rust packages. Use this
template to quickly get started with a new Rust project as well as having the
infrastructure configuration files to make developing and building Rust packages
easier.

## Features

These are the features included in this template that help with building and
maintaining a Rust package. Depending on the answers given to the template
questions, some of these features may not be included in the created project:

- Uses [Quarto](https://quarto.org/) Markdown for the website content, allowing
  for easy integration of code, text, and figures.
- Includes a [justfile](https://just.systems/man/en/) for managing common tasks
  like building the website and running checks.
- Uses [typos](https://github.com/crate-ci/typos) to check for common spelling
  mistakes.
- Uses
  [git-cliff](https://decisions.seedcase-project.org/why-changelog-with-git-cliff/)
  to automatically create the changelog.
- Automates Git tagging and GitHub releases with
  [Cocogitto](https://decisions.seedcase-project.org/why-semantic-release-with-cocogitto/)
  that are based on messages following [Conventional
  Commits](https://decisions.seedcase-project.org/why-conventional-commits/).
- Uses a [MIT](https://decisions.seedcase-project.org/why-mit-license/) license.
- Run checks with [pre-commit](https://pre-commit.com/) hooks to ensure
  consistent formatting and style across the project. It includes checks for
  credentials, typos, and file formatting.
- Optionally uses the
  [`seedcase-theme`](https://github.com/seedcase-project/seedcase-theme) Quarto
  extension for a standard appearance across websites.
- Includes [GitHub Actions](https://docs.github.com/en/actions) for continuous
  integration, testing, and delivery for running checks, formatting, releasing,
  and building the website. It also includes
  [Dependabot](https://docs.github.com/en/code-security/tutorials/secure-your-dependencies/dependabot-quickstart-guide)
  for keeping GitHub Action dependencies up to date.
- Options between [Netlify](https://www.netlify.com/) or [GitHub
  Pages](https://pages.github.com/) for hosting the website. For dealing with
  custom domain names, Netlify is the better choice, as the configuration is
  very easy to set up.
- Includes an [EditorConfig](https://editorconfig.org/) file to ensure
  consistent formatting across different editors.
- High-level system and program management with
  [uv](https://decisions.seedcase-project.org/why-uv/).
- GitHub workflows for automatically adding Pull Requests and Issues to a
  project board.
- Pull request template for easy creation of new Pull Requests.
- [VS Code](https://code.visualstudio.com/) settings commonly used by
  contributors working in VS Code.
- [`CITATION.cff`](https://citation-file-format.github.io) file for citation
  information that provides Zenodo with the necessary metadata to create a DOI
  for the project and for GitHub to display the citation information on the
  repository page.
- Includes a [GoatCounter](https://www.goatcounter.com/) file for website
  visitor tracking, which is privacy-friendly and does not use cookies. That
  means it doesn't need a GDPR notice as no personal data is collected.
- Uses [rumdl](https://rumdl.dev) and [Panache](https://panache.bz) to format
  Markdown files, so that they are consistent across the repository and easier
  to read in the raw form. We use two because they both do slightly different
  things for Quarto Markdown files. Rumdl is better at linting, while Panache is
  better at formatting.
- Uses [lychee](https://lychee.cli.rs) to check for broken links in the website
  files.

## Want to contribute?

We would love your feedback or contributions! Head over to our [GitHub
repository]({{< meta links.github >}}) to share your ideas or contribute code.
Your input makes us better!

::: content-hidden
### Contributors

{{< include /docs/includes/_contributors.qmd >}}
:::

## Licensing

This project is licensed under the [MIT License](/LICENSE.md).
